---
title: Alternative Procedure To Creation Scientific Reports
date : 2021-04-03
author: Peter von rohr
output: html_document
---


# Disclaimer
Thoughts and arguments why alternative procedures to create scientific reports are important.


# Background
Traditionally, reports are generated by running some data analysis in R or in other specialiced software packages. The results of these analyses are written to text files. From these output files, the relevant results are copied and pasted into a document of a common text-processing system. The report is written in the word-processing system. In addition to the shown results, diagrams and graphics might also be added into the report using the copy-paste procedure. The final version of the report can be sent out to customers or clients. 

If we are going to write every report from the beginning to the end only once that previously described procedure based on copy-pasting all elements of the report together in one final document would be ok. But most reports are produced iteratively. Very often after a first draft, other people will comment on the draft and will require some changes to the report. With the copy-paste procedure, this basically comes to re-doing almost the whole report again. This is tedious and can lead to inconsistencies, if some parts of the report are not updated and not adpated to the required changes. 

Furthermore, some of the widely used text-processing systems do not provide good support to creating reproducible versions of reports. 


# Alternative
The lack of good support of reprocibility and the unflexibility of the copy-paste procedure make it necessary to think about alternative creation procedures for scientific reports. One such alternative is described in this section.


